teams_dict = {
    "Olimpija": "Olimpija Ljubljana",
    "KD Olimpija": "Olimpija Ljubljana",
    "Vega Olimpija": "Olimpija Ljubljana",
    "SCT Olimpija": "Olimpija Ljubljana",
    "Rudar": "Rudar Velenje",
    "Rudar V.": "Rudar Velenje",
    "BS Tehnik Domžale": "Domžale",
    "HIT Gorica": "Gorica",
    "Hit Gorica": "Gorica",
    "ND Gorica": "Gorica",
    "SAOP Gorica": "Gorica",
    "Maribor Pivovarna Laško": "Maribor",
    "Maribor Teatanic": "Maribor",
    "Maribor Branik": "Maribor",
    "Triglav": "Triglav Kranj",
    "Živila Triglav": "Triglav Kranj",
    "Triglav Gorenjska": "Triglav Kranj",
    "CM Celje": "Celje",
    "MIK CM Celje": "Celje",
    "CMC Publikum": "Celje",
    "Publikum": "Celje",
    "Protonavto Publikum": "Celje",
    "Biostart Publikum": "Celje",
    "Luka Koper": "Koper",
    "Anet Koper": "Koper",
    "FC Koper": "Koper",
    "Sport Line Koper": "Koper",
    "Istrabenz Koper": "Koper",
    "Krka Novoterm": "Krka",
    "Studio D Novo mesto": "Krka",
    "Nafta Lendava": "Nafta",
    "Labod Drava Ptuj": "Labod Drava",
    "Drava Ptuj": "Labod Drava",
    "Drava": "Labod Drava",
    "Kumho Drava": "Labod Drava",
    "AM Cosmos Ljubljana": "Ljubljana",
    "Eurospekter Ljubljana": "Ljubljana",
    "Železničar Oscar": "Ljubljana",
    "Elektroelement Zagorje": "Zagorje",
    "Era Šmartno": "Šmartno",
    "Dravograd": "Koroška Dravograd",
    "Korotan": "Relax Korotan",
    "Mag Korotan": "Relax Korotan",
    "Korotan Suvel": "Relax Korotan",
    "AS Beltinci": "Potrošnik Beltinci",
    "Beltinci": "Potrošnik Beltinci",
    "Vevče": "Set Vevče",
    "Belvedur Izola": "Izola",
    "Istragas Jadran": "Jadran Dekani",
    "Jadran Lama": "Jadran Dekani",
    "Kompas Holidays Svoboda": "Optimizem Svoboda",
    "Liqui Moly Svoboda": "Optimizem Svoboda",
}
